services:
  db:
    image: postgres
    container_name: db
    env_file: ./back-end/.env.db
    environment:
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - app-network
    ports:
      - "5433:5432"

  backend:
    build: ./back-end
    container_name: backend
    ports:
    - "3000:3000"
    depends_on:
      - db
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./back-end/.env.dev
    volumes:
      - ./back-end:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "3003:3003"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
